version: '3'
services:
  app:
    image: products-app:1.0
    build: .
    ports:
      - "8000:8000"
      - "9229:9229"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: postgres
    volumes:
        - ./src:/app/src
